apiVersion: apps/v1
kind: Deployment
metadata:
  name: ###
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ###
  template:
    metadata:
      name: ###
      labels:
        app: ###
    spec:
      containers:
      - name: ###
        image: ###/cit-270-1999
        volumeMounts:
        - name: ssl
          mountPath: "/usr/src/app/SSL"
        command: ["npm"]
        args: ["run", "start"]
        resources:
          requests:
            cpu: .125
            memory: "500Mi"
          limits:
            cpu: .125
            memory: "600Mi"
        imagePullPolicy: IfNotPresent
      volumes:
      - name: ssl
        secret:
          secretName: ssl.secret.nathanaelbudge